### ISSUE TITLE
zipfile.BadZipFile: Bad magic number for file header

### ISSUE THREAD

**Issue by AlfredoCubitos** [Amourspirit/python_libreoffice_oooscript#23]
I tried to build the example from here:
[python-ooouno-ex](https://github.com/Amourspirit/python-ooouno-ex/tree/main/ex/general/python_sample)
I get the following error:

```
File "/usr/lib64/python3.11/zipfile.py", line 1755, in _extract_member
    with self.open(member, pwd=pwd) as source, \
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/zipfile.py", line 1585, in open
    raise BadZipFile("Bad magic number for file header")
zipfile.BadZipFile: Bad magic number for file header
make: *** [Makefile:8: build] Fehler 1
```
any idea whats going wrong?

**Comment by Amourspirit** [comment]
I have not been able to reproduce this error.

OooScript was just updated yesterday. I have added the new version to [Live LibreOffice Python UNO Examples](https://github.com/Amourspirit/python-ooouno-ex/tree/main). Pull the latest version and try again.

**Comment by AlfredoCubitos** [comment]
I found the problem.
The` sample.odt` file was corrupt.
I changed the file, and it works :-)
